=== ClimateChangeInstitute/anttframework/AntT/WebContent/methodology.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT methodology (paper*)>
<!ELEMENT paper (title,description,doc)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT doc (url)>
<!ELEMENT url (#PCDATA)>

=== ClimateChangeInstitute/anttframework/AntT/WebContent/methodology.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE methodology SYSTEM "methodology.dtd">
<methodology>
	<!-- This is an example xml template - it is a way to define your papers -->
	<!-- You may leave out the tags that you don't have information for or that 
		you don't want to include. -->
	<paper>
		<title>Ice Core Sample Preparation</title>
		<description>Instructions of sample preparation technique to mount tephra 
		particles extracted from ice cores. This technique was developed to ensure any size 
		particle can be captured. Last update: June 16, 2017.</description>
		<doc>
			<url>./content/IceCoreMountingTechnique06162017.pdf</url>
		</doc>
	</paper>
	<paper>
		<title>AntT system software design </title>
		<description>
		AnnT design and source code details are available on GitHub.
		</description>
		<doc>
			<url>https://github.com/ClimateChangeInstitute/anttframework</url>
		</doc>
	</paper>
	<paper>
		<title>"Advancements and best practices for..." - Iverson et al.,2016</title>
		<description>
		Description of how to prepare and analyze fine-grained tephra
		particles (less than 20um) extracted from ice cores. Several analytical methods 
		described are: EMP-WDS, SEM-EDS, LA-ICP-MS, and SIMS.</description>
		<doc>
			<url>http://www.sciencedirect.com/science/article/pii/S1871101416301467</url>
		</doc>
	</paper>
	<paper>
		<title>"Tephra layers in the Siple Dome..." - Dunbar et al., 2003</title>
		<description>First tephrochronological study of Siple Dome  (Antarctica) ice core.</description>
		<doc>
			<url>http://onlinelibrary.wiley.com/doi/10.1029/2002JB002056/full</url>
		</doc>
	</paper>
	<paper>
		<title>Borchardt et al., 1972</title>
		<description>Borchardt, G., P. Aruscavage, and H. Millard (1972), Correlation of the Bishop ash, a Pleistocene marker bed, using instrumental neutron activation analysis, Journal of Sedimentary Petrology, 42(2), 301â€“306, doi:10.1306/74D72527-2B21-11D7-8648000102C1865D..</description>
		<doc>
			<url>http://jsedres.geoscienceworld.org/content/42/2/301</url>
		</doc>
	</paper>
</methodology>
