=== ClimateChangeInstitute/anttframework/AntT/WebContent/team.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT team (member*)>
<!ELEMENT member (name,url?,email?,other?,image?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT other (#PCDATA)>
<!ELEMENT image (url,title,alt)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT alt (#PCDATA)>

=== ClimateChangeInstitute/anttframework/AntT/WebContent/team.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE team SYSTEM "team.dtd">
<team>
	<!-- This is an example xml template - it is a way to define your members -->
	<member>
		<name>Nelia W. Dunbar</name>
		<url>http://geoinfo.nmt.edu/staff/dunbar</url>
		<email>nelia@nmbg.nmt.edu</email>
		<other>New Mexico Bureau of Geology and Mineral Resources 
Earth and Environmental Science Department, New Mexico Tech.</other>
		<image>
			<url>./index_files/images/NWD-2016.jpg</url>
			<title>Dr. Nelia Dunbar</title>
			<alt>Image</alt>
		</image>
	</member>
	<member>
		<name>Mark Royer</name>
		<url>http://aturing.umcs.maine.edu/~mark.royer/</url>
		<email>mroyer@cs.umaine.edu</email>
		<other>The Department of Computer Science, University of Maine.</other>
		<image>
			<url>./index_files/images/MR.jpg</url>
			<title>member2</title>
			<alt>Member2</alt>
		</image>
	</member>
	<member>
		<name>Member 3</name>
		<url>http://somememberssite.com</url>
		<email>member3@maine.edu</email>
		<other>Some more text</other>
		<image>
			<url>./index_files/images/team_member_375.png</url>
			<title>Member 3</title>
			<alt>Member 3</alt>
		</image>
	</member>
	<member>
		<name>Member 3</name>
		<url>http://somememberssite.com</url>
		<email>member3@maine.edu</email>
		<other>Some more text</other>
		<image>
			<url>./index_files/images/team_member_375.png</url>
			<title>Member 3</title>
			<alt>Member 3</alt>
		</image>
	</member>
</team>
